# Generated by Django 5.2 on 2025-04-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ingredients', models.TextField(help_text='Enter ingredients separated by commas')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('calorie_count', models.IntegerField(help_text='Calories in kcal')),
                ('cooking_time', models.IntegerField(help_text='Time in minutes')),
                ('allergic_content', models.CharField(blank=True, max_length=255, null=True)),
                ('cooking_method', models.TextField(help_text='Enter steps separated by commas')),
                ('category', models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian')], default='veg', help_text='Select whether the recipe is Veg or Non-Veg', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
