# Generated by Django 5.2 on 2025-05-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0006_alter_like_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
